### PR TITLE
Safely cast the malloc() to char*

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by Murii** [comment]
Thanks for the submit but casting "malloc" in C is not a good idea.

**Comment by RobLoach** [comment]
Was getting a cast warning. Was not quite sure if the best way to deal with it.

**Comment by Murii** [comment]
You're using Visual Studio?

**Comment by RobLoach** [comment]
gcc on Linux. I added `-fpermissive` to ignore the warning. Closing this one for now.

**Pull request closed without merging**
